"use client";

import { useEffect, useState } from "react";
import { Router, Plus, MapPin, MoreVertical, RefreshCw } from "lucide-react";

interface Router { id: string; name: string; brand: string; address: string; status: "online" | "offline" | "not_connected"; createdAt: string; }

export default function RoutersPage() {
  const [routers, setRouters] = useState<Router[]>([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [formData, setFormData] = useState({ name: "", brand: "", address: "" });
  useEffect(() => { fetchRouters(); }, []);
  const fetchRouters = async () => { try { const res = await fetch("/api/routers"); const data = await res.json(); if (data.success) setRouters(data.data.routers); } catch (error) { console.error("Failed to fetch routers", error); } finally { setLoading(false); } };
  const handleAddRouter = async (e: React.FormEvent) => { e.preventDefault(); try { const res = await fetch("/api/routers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(formData) }); const data = await res.json(); if (data.success) { setRouters([...routers, data.data]); setFormData({ name: "", brand: "", address: "" }); setShowModal(false); } } catch (error) { console.error("Failed to add router", error); } };
  const getStatusColor = (status: string) => status === "online" ? "badge-success" : status === "offline" ? "badge-danger" : "badge-warning";

  return <main className="admin-light min-h-screen"><div className="flex min-h-screen flex-col">
    <header className="sticky top-0 z-20 border-b border-[#252525] bg-[#0b0b0b]/95 px-5 py-4 sm:px-8"><div className="flex items-center justify-between gap-4"><div><p className="text-sm-caps text-orange-500">Network Infrastructure</p><h1 className="text-2xl font-black text-white">Network Routers</h1><p className="mt-1 text-sm text-gray-500">Manage connected routers and deployment locations.</p></div><div className="flex gap-2"><button onClick={fetchRouters} className="flames-button-secondary p-3" aria-label="Refresh routers"><RefreshCw size={16}/></button><button onClick={() => setShowModal(true)} className="flames-button flex items-center gap-2"><Plus size={18}/>Add Router</button></div></div></header>
    <div className="flex-1 px-5 py-6 sm:px-8">{loading ? <div className="flex justify-center py-12"><p className="text-gray-500">Loading routers...</p></div> : routers.length === 0 ? <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#292929] bg-white py-16"><Router size={32} className="mb-3 text-sky-500"/><p className="font-medium text-gray-500">No routers configured</p><p className="mt-1 text-sm text-gray-600">Connect your first router to get started.</p><button onClick={() => setShowModal(true)} className="flames-button mt-4">Add Router</button></div> : <div className="grid gap-5 lg:grid-cols-2">{routers.map((router)=><div key={router.id} className="flames-card"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-sky-50 text-sky-600"><Router size={20}/></div><span className={`badge ${getStatusColor(router.status)}`}>{router.status.replace("_"," ")}</span></div><h3 className="mt-4 text-lg font-bold text-slate-900">{router.name}</h3><p className="mt-1 text-sm text-slate-500">{router.brand}</p><div className="mt-4 flex items-center gap-2 text-sm text-slate-600"><MapPin size={16}/>{router.address}</div><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4"><div className="text-xs text-slate-500">Router ID <span className="font-medium text-slate-700">{router.id}</span></div><div className="flex gap-2"><button className="flames-button-secondary">Edit</button><button className="rounded-lg p-2 hover:bg-slate-100" aria-label={`More actions for ${router.name}`}><MoreVertical size={18} className="text-slate-500"/></button></div></div></div>)}</div>}</div>
  </div>
  {showModal && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="flames-card w-full max-w-md"><h2 className="mb-4 text-xl font-black text-slate-900">Add Router</h2><form onSubmit={handleAddRouter} className="space-y-4"><div><label className="mb-2 block text-sm font-medium text-slate-600">Router Name</label><input type="text" required value={formData.name} onChange={(e)=>setFormData({...formData,name:e.target.value})} className="flames-input" placeholder="Main Office"/></div><div><label className="mb-2 block text-sm font-medium text-slate-600">Router Brand / Model</label><input type="text" required value={formData.brand} onChange={(e)=>setFormData({...formData,brand:e.target.value})} className="flames-input" placeholder="TP-Link Archer C7"/></div><div><label className="mb-2 block text-sm font-medium text-slate-600">Location / Address</label><input type="text" required value={formData.address} onChange={(e)=>setFormData({...formData,address:e.target.value})} className="flames-input" placeholder="Westlands, Nairobi"/></div><div className="flex gap-3 pt-4"><button type="button" onClick={()=>setShowModal(false)} className="flames-button-secondary flex-1">Cancel</button><button type="submit" className="flames-button flex-1">Add Router</button></div></form></div></div>}
  </main>;
}
