"use client";

import { useEffect, useState } from "react";
import { CreditCard, MoreVertical, RefreshCw } from "lucide-react";

interface Payment { id: string; customerId: string; packageId: string; amount: number; method: "mpesa" | "card" | "bank" | "other"; status: "pending" | "successful" | "failed"; transactionId?: string; createdAt: string; }

export default function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(true);
  const [totalRevenue, setTotalRevenue] = useState(0);
  useEffect(() => { fetchPayments(); }, []);
  const fetchPayments = async () => { try { const res = await fetch("/api/payments"); const data = await res.json(); if (data.success) { setPayments(data.data.payments); setTotalRevenue(data.data.revenue); } } catch (error) { console.error("Failed to fetch payments", error); } finally { setLoading(false); } };
  const getStatusBadgeColor = (status: string) => status === "successful" ? "badge-success" : status === "pending" ? "badge-warning" : status === "failed" ? "badge-danger" : "badge-primary";

  return <main className="admin-light min-h-screen"><div className="flex min-h-screen flex-col">
    <header className="sticky top-0 z-20 border-b border-[#252525] bg-[#0b0b0b]/95 px-5 py-4 sm:px-8"><div className="flex items-center justify-between gap-4"><div><p className="text-sm-caps text-orange-500">Finance</p><h1 className="text-2xl font-black text-white">Payments</h1><p className="mt-1 text-sm text-gray-500">Track hotspot transactions and payment status.</p></div><div className="flex items-center gap-3"><div className="rounded-lg border border-slate-200 bg-white px-4 py-2"><p className="text-xs text-slate-500">Total Revenue</p><p className="text-lg font-black text-slate-900">KES {totalRevenue.toLocaleString()}</p></div><button onClick={fetchPayments} className="flames-button-secondary p-3" aria-label="Refresh payments"><RefreshCw size={16}/></button></div></div></header>
    <div className="flex-1 px-5 py-6 sm:px-8">{loading ? <div className="flex justify-center py-12"><p className="text-gray-500">Loading payments...</p></div> : payments.length === 0 ? <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#292929] bg-white py-16"><CreditCard size={32} className="mb-3 text-orange-500"/><p className="font-medium text-gray-500">No payments yet</p><p className="mt-1 text-sm text-gray-600">Payment history will appear here.</p></div> : <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Transaction</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{payments.map((payment)=><tr key={payment.id} className="hover:bg-slate-50"><td className="px-5 py-4"><span className="font-semibold text-slate-900">{payment.transactionId || payment.id}</span><p className="mt-1 text-xs text-slate-500">Package {payment.packageId}</p></td><td className="px-5 py-4 text-slate-600">{payment.customerId}</td><td className="px-5 py-4 text-slate-600">{payment.method.toUpperCase()}</td><td className="px-5 py-4 font-bold text-slate-900">KES {payment.amount.toLocaleString()}</td><td className="px-5 py-4 text-slate-600">{new Date(payment.createdAt).toLocaleDateString()}</td><td className="px-5 py-4"><span className={`badge ${getStatusBadgeColor(payment.status)}`}>{payment.status}</span></td><td className="px-5 py-4 text-right"><button className="rounded-lg p-2 hover:bg-slate-100" aria-label="Payment actions"><MoreVertical size={18} className="text-slate-500"/></button></td></tr>)}</tbody></table></div>}</div>
  </div></main>;
}
