"use client";

import Link from "next/link";
import { Activity, CircleDollarSign, LayoutDashboard, Users, Wifi, Router, Package, CreditCard, BarChart3, Settings, Menu, Bell, ShieldCheck, ArrowUpRight } from "lucide-react";
import { useState } from "react";

const menuItems = [
  { name: "Overview", href: "/", icon: LayoutDashboard }, { name: "Customers", href: "/customers", icon: Users }, { name: "Packages", href: "/packages", icon: Package }, { name: "Sessions", href: "/sessions", icon: Wifi }, { name: "Payments", href: "/payments", icon: CreditCard }, { name: "Routers", href: "/routers", icon: Router }, { name: "Reports", href: "/reports", icon: BarChart3 }, { name: "Settings", href: "/settings", icon: Settings },
];
const quickActions = [
  { href: "/customers", icon: Users, title: "Customers", desc: "Manage hotspot users and accounts." }, { href: "/packages", icon: Package, title: "Packages", desc: "Create plans, prices and durations." }, { href: "/routers", icon: Router, title: "Routers", desc: "Manage network hardware and locations." }, { href: "/payments", icon: CreditCard, title: "Payments", desc: "Review transactions and revenue." },
];
const stats = [
  { label: "Active Users", value: "0", detail: "Currently connected", icon: Users, tone: "orange" }, { label: "Revenue Today", value: "KES 0", detail: "Successful payments", icon: CircleDollarSign, tone: "green" }, { label: "Online Sessions", value: "0", detail: "Active sessions", icon: Activity, tone: "blue" }, { label: "Connected Routers", value: "0", detail: "Network devices online", icon: Router, tone: "orange" },
];

function Sidebar({ mobile = false, onClose }: { mobile?: boolean; onClose?: () => void }) {
  return <aside className={`${mobile ? "w-full" : "hidden w-64 md:block"} sticky top-0 h-screen shrink-0 overflow-y-auto border-r border-slate-800 bg-[#111827] p-5 text-white`}>
    <div className="mb-8 flex items-center justify-between px-2"><Link href="/" onClick={onClose} className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-orange-500 text-sm font-black text-white">FT</div><div><p className="text-lg font-black tracking-tight">FLAMMES</p><p className="text-[10px] font-bold tracking-[0.25em] text-sky-400">TECH • HOTSPOT</p></div></Link>{mobile && <button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-800 hover:text-white" aria-label="Close menu">×</button>}</div>
    <p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[0.14em] text-slate-500">Management</p>
    <nav className="space-y-1">{menuItems.map((item) => { const Icon = item.icon; const active = item.href === "/"; return <Link key={item.name} href={item.href} onClick={onClose} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active ? "bg-orange-500 text-white" : "text-slate-300 hover:bg-slate-800 hover:text-white"}`}><Icon size={18}/><span>{item.name}</span></Link>; })}</nav>
    <div className="mt-8 rounded-xl border border-slate-700 bg-slate-800/60 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-500">System status</p><div className="mt-3 flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-green-500"/><span className="text-sm font-semibold">System online</span></div><p className="mt-1 text-xs text-slate-400">Ready for operations</p></div>
  </aside>;
}

export default function Dashboard() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="flex min-h-screen"><Sidebar />{mobileMenuOpen && <div className="fixed inset-0 z-50 bg-slate-900/40 md:hidden"><div className="h-full w-72"><Sidebar mobile onClose={() => setMobileMenuOpen(false)}/></div></div>}<section className="min-w-0 flex-1">
    <header className="sticky top-0 z-30 flex h-[73px] items-center justify-between border-b border-slate-200 bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileMenuOpen(true)} className="rounded-lg border border-slate-200 p-2 text-slate-600 md:hidden" aria-label="Open menu"><Menu size={20}/></button><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-orange-600">Administration</p><h1 className="text-lg font-bold text-slate-900">Dashboard</h1></div></div><button className="relative rounded-lg border border-slate-200 bg-white p-2.5 text-slate-600 hover:bg-slate-50" aria-label="Notifications"><Bell size={18}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-orange-500"/></button></header>
    <div className="mx-auto max-w-[1500px] p-5 sm:p-8">
      <section className="mb-6 rounded-xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex flex-wrap items-center gap-3"><span className="badge badge-primary">FLAMMES HOTSPOT</span><span className="flex items-center gap-2 text-xs font-semibold text-green-700"><span className="status-dot status-dot-online"/>Operational</span></div><div className="mt-4 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><h2 className="text-2xl font-black tracking-tight text-slate-900 sm:text-3xl">Hotspot operations center</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Monitor customers, sessions, payments and network infrastructure from one structured workspace.</p></div><Link href="/sessions" className="flames-button inline-flex items-center gap-2">View live sessions<ArrowUpRight size={16}/></Link></div></section>
      <section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat)=>{const Icon=stat.icon; const iconClass=stat.tone === "green" ? "bg-green-50 text-green-600" : stat.tone === "blue" ? "bg-sky-50 text-sky-600" : "bg-orange-50 text-orange-600"; return <div key={stat.label} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-lg ${iconClass}`}><Icon size={19}/></div><span className="badge badge-success">Live</span></div><p className="mt-4 text-sm font-medium text-slate-500">{stat.label}</p><p className="mt-1 text-2xl font-black text-slate-900">{stat.value}</p><p className="mt-1 text-xs text-slate-400">{stat.detail}</p></div>})}</section>
      <section className="mb-7"><div className="mb-4"><p className="text-sm-caps text-orange-600">Control center</p><h2 className="mt-1 text-xl font-black text-slate-900">Quick access</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{quickActions.map((action)=>{const Icon=action.icon; return <Link key={action.href} href={action.href} className="flames-card group"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-orange-50 text-orange-600"><Icon size={19}/></div><h3 className="mt-4 font-bold text-slate-900 group-hover:text-orange-600">{action.title}</h3><p className="mt-1 text-sm leading-5 text-slate-500">{action.desc}</p><div className="mt-4 flex items-center gap-1 text-xs font-semibold text-orange-600">Open module<ArrowUpRight size={13}/></div></Link>})}</div></section>
      <section className="grid gap-5 lg:grid-cols-3"><div className="flames-card lg:col-span-2 !p-0 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="text-sm-caps text-orange-600">Network operations</p><h2 className="mt-1 text-lg font-black text-slate-900">Live sessions</h2></div><Link href="/sessions" className="text-xs font-semibold text-orange-600 hover:text-orange-700">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Package</th><th className="px-5 py-3">Router</th><th className="px-5 py-3">Status</th></tr></thead><tbody><tr><td colSpan={4} className="px-5 py-12 text-center"><Wifi size={28} className="mx-auto mb-2 text-slate-300"/><p className="font-medium text-slate-500">No active sessions</p><p className="mt-1 text-xs text-slate-400">Connected customers will appear here.</p></td></tr></tbody></table></div></div><div className="flames-card"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-50 text-green-600"><ShieldCheck size={19}/></div><div><p className="text-sm-caps text-slate-400">Infrastructure</p><h2 className="text-lg font-black text-slate-900">Network status</h2></div></div><div className="mt-5 space-y-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Platform</span><span className="flex items-center gap-2 text-xs font-bold text-green-700"><span className="status-dot status-dot-online"/>Online</span></div><div className="divider"/><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Database</span><span className="flex items-center gap-2 text-xs font-bold text-green-700"><span className="status-dot status-dot-online"/>Ready</span></div><div className="divider"/><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Routers</span><span className="text-sm font-bold text-slate-900">0 online</span></div></div><Link href="/routers" className="flames-button-secondary mt-6 flex w-full items-center justify-center gap-2">Manage routers<ArrowUpRight size={15}/></Link></div></section>
      <section className="mt-5 flames-card !p-0 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="text-sm-caps text-orange-600">Finance</p><h2 className="mt-1 text-lg font-black text-slate-900">Recent payments</h2></div><Link href="/payments" className="text-xs font-semibold text-orange-600">View all</Link></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Transaction</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Status</th></tr></thead><tbody><tr><td colSpan={4} className="px-5 py-10 text-center"><CreditCard size={26} className="mx-auto mb-2 text-slate-300"/><p className="font-medium text-slate-500">No payments recorded</p><p className="mt-1 text-xs text-slate-400">Transactions will appear here after payment processing.</p></td></tr></tbody></table></div></section>
    </div></section></div></main>;
}
