import { useEffect, useState } from 'react';
import { api } from '@appdeploy/client';
import { Activity, CircleDot, Link2, Plus, RefreshCw, Router, ShieldCheck, Wifi, X } from 'lucide-react';

type AP={id:string;name:string;vendor:string;model?:string;macAddress?:string;ipAddress?:string;location:string;status:string;routerName?:string;credentialsConfigured?:boolean;connectedClients?:number;rxMbps?:number;txMbps?:number;lastSeenAt?:number;parentInterfaceName?:string};
type Topology={routers:any[];accessPoints:AP[];links:any[];liveDiscovery:any[];generatedAt:number;note:string};
type Earnings={date:string;rows:{accessPointId:string;name:string;location:string;revenue:number;transactions:number;customers:number}[];totalRevenue:number;unattributedRevenue:number};

const money=(n:number)=>`KES ${n.toLocaleString()}`;

export default function NetworkTopologyAdmin(){
 const [data,setData]=useState<Topology|null>(null); const [earnings,setEarnings]=useState<Earnings|null>(null); const [busy,setBusy]=useState(false); const [show,setShow]=useState(false); const [message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',vendor:'Tenda',model:'',macAddress:'',ipAddress:'',location:'',routerId:'',parentInterfaceName:'',managementProtocol:'unknown'});
 const load=async()=>{setBusy(true);try{const [t,e]=await Promise.all([api.get('/api/access-points/topology'),api.get('/api/analytics/ap-earnings')]);setData(t.data);setEarnings(e.data);}catch(err){setMessage(err instanceof Error?err.message:'Unable to load topology.');}finally{setBusy(false);}};
 useEffect(()=>{void load();},[]);
 const register=async()=>{if(!form.name||!form.vendor||!form.location){setMessage('AP name, vendor and location are required.');return;}setBusy(true);try{await api.post('/api/access-points',form);setShow(false);setForm({name:'',vendor:'Tenda',model:'',macAddress:'',ipAddress:'',location:'',routerId:'',parentInterfaceName:'',managementProtocol:'unknown'});await load();setMessage('Access point registered.');}catch(err){setMessage(err instanceof Error?err.message:'Unable to register AP.');}finally{setBusy(false);}};
 const routerById=(id:string)=>data?.routers.find(r=>r.id===id)?.name||'Unassigned';
 return <section className="panel full-page-panel">
  <div className="page-header"><div><span className="section-kicker">NETWORK TOPOLOGY</span><h1>Router → Access Point Map</h1><p>Live discovery plus explicitly configured links. Unknown links are never invented.</p></div><div className="page-header-actions"><button className="secondary-action" onClick={()=>void load()} disabled={busy}><RefreshCw size={15}/> Refresh</button><button className="primary-action" onClick={()=>setShow(true)}><Plus size={15}/> Register AP</button></div></div>
  {message&&<div className="integration-note"><ShieldCheck size={17}/><div><strong>Network status</strong><p>{message}</p></div><button className="icon-close" onClick={()=>setMessage('')}><X size={15}/></button></div>}
  <div className="topology-summary"><div><span>Routers</span><strong>{data?.routers.length??0}</strong></div><div><span>Access Points</span><strong>{data?.accessPoints.length??0}</strong></div><div><span>Discovered Links</span><strong>{(data?.liveDiscovery.length??0)+(data?.links.length??0)}</strong></div><div><span>Today's AP Revenue</span><strong>{money(earnings?.totalRevenue??0)}</strong></div></div>
  <div className="topology-map">{data?.routers.map(r=><div className="topology-router" key={r.id}><Router size={22}/><div><strong>{r.name}</strong><small>{r.vendor} • {r.location}</small></div><span>{r.status}</span><div className="topology-children">{data.accessPoints.filter(ap=>ap.routerId===r.id).map(ap=><div className="topology-ap" key={ap.id}><Wifi size={17}/><div><strong>{ap.name}</strong><small>{ap.vendor}{ap.model?' • '+ap.model:''} • {ap.location}</small><small>{ap.parentInterfaceName||'parent interface unknown'} • {ap.connectedClients??0} clients</small></div><em className={ap.status==='online'?'health-online':'health-unknown'}><CircleDot size={12}/>{ap.status}</em></div>)}{!data.accessPoints.some(ap=>ap.routerId===r.id)&&<div className="empty-inline">No AP explicitly assigned to this router.</div>}</div></div>)}</div>
  <div className="feature-grid"><div className="feature"><Link2 size={18}/><strong>Live discovery</strong><small>{data?.liveDiscovery.length??0} RouterOS neighbor records returned by real hardware.</small></div><div className="feature"><Activity size={18}/><strong>Performance</strong><small>Client, traffic and health fields are shown when the AP management path exposes them.</small></div><div className="feature"><ShieldCheck size={18}/><strong>Credentials</strong><small>AP credentials are backend-only and never displayed.</small></div></div>
  <div className="panel-section"><div className="panel-section-head"><div><span className="section-kicker">DAILY REVENUE</span><h3>Calculated from transactions</h3><p>No daily revenue snapshots are stored.</p></div></div><div className="record-list">{earnings?.rows.map(row=><div className="record-row" key={row.accessPointId}><span className="row-icon"><Wifi size={16}/></span><div><strong>{row.name}</strong><small>{row.location} • {row.transactions} paid transactions • {row.customers} customers</small></div><em className="status-pill online"><i/>LIVE CALC</em><b>{money(row.revenue)}</b></div>)}{earnings?.unattributedRevenue ? <div className="integration-note"><CircleDot size={16}/><div><strong>Unattributed revenue</strong><p>{money(earnings.unattributedRevenue)} was paid without an AP identity and is intentionally not assigned to an AP.</p></div></div>:null}</div></div>
  {show&&<div className="modal-backdrop" onMouseDown={()=>setShow(false)}><div className="edit-modal" onMouseDown={e=>e.stopPropagation()}><div className="edit-modal-head"><div><span className="section-kicker">REGISTER AP</span><h2>Universal Access Point</h2><p>Works with Tenda and any other AP vendor with a usable management/discovery path.</p></div><button className="icon-close" onClick={()=>setShow(false)}><X size={18}/></button></div><div className="edit-form"><label>AP name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} autoFocus/></label><div className="form-two"><label>Vendor<input value={form.vendor} onChange={e=>setForm({...form,vendor:e.target.value})}/></label><label>Model<input value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></label></div><div className="form-two"><label>MAC address<input value={form.macAddress} onChange={e=>setForm({...form,macAddress:e.target.value.toUpperCase()})} placeholder="AA:BB:CC:DD:EE:FF"/></label><label>Management IP<input value={form.ipAddress} onChange={e=>setForm({...form,ipAddress:e.target.value})}/></label></div><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><div className="form-two"><label>Parent router<select value={form.routerId} onChange={e=>setForm({...form,routerId:e.target.value})}><option value="">Unassigned</option>{data?.routers.map(r=><option key={r.id} value={r.id}>{r.name} • {r.location}</option>)}</select></label><label>Parent interface<input value={form.parentInterfaceName} onChange={e=>setForm({...form,parentInterfaceName:e.target.value})} placeholder="ether2"/></label></div><label>Management protocol<select value={form.managementProtocol} onChange={e=>setForm({...form,managementProtocol:e.target.value})}><option value="unknown">Unknown / Gateway</option><option value="api">API</option><option value="snmp">SNMP</option><option value="http_api">HTTP API</option><option value="controller">Controller</option><option value="gateway">Gateway Agent</option></select></label><small>Credentials are intentionally not collected in browser forms. Provision AP secrets through the secure backend secret mechanism.</small></div><div className="edit-modal-actions"><button className="secondary-action" onClick={()=>setShow(false)}>Cancel</button><button className="primary-action" onClick={()=>void register()} disabled={busy}>Register AP</button></div></div></div>}
 </section>;
}
